//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ksmirnov
{
    using System;
    using System.Collections.Generic;
    
    public partial class IbgridientsSmirnov
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IbgridientsSmirnov()
        {
            this.ingridientsProductSmirnov = new HashSet<ingridientsProductSmirnov>();
        }
    
        public string Product { get; set; }
        public string units { get; set; }
        public double price { get; set; }
        public double count { get; set; }
        public int id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ingridientsProductSmirnov> ingridientsProductSmirnov { get; set; }
    }
}
