//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ksmirnov
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bakery_kpEntities1 : DbContext
    {
        public bakery_kpEntities1()
            : base("name=bakery_kpEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IbgridientsSmirnov> IbgridientsSmirnov { get; set; }
        public virtual DbSet<ingridientsProductSmirnov> ingridientsProductSmirnov { get; set; }
        public virtual DbSet<ProductSmirnov> ProductSmirnov { get; set; }
    }
}
