//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ksmirnov.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingridientsProduct
    {
        public int ProductId { get; set; }
        public int IngridientsId { get; set; }
        public double Count { get; set; }
        public int id { get; set; }
    
        public virtual IbgridientsSmirnov IbgridientsSmirnov { get; set; }
        public virtual ProductSmirnov ProductSmirnov { get; set; }
    }
}
