//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ksmirnov.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSmirnov
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductSmirnov()
        {
            this.ingridientsProduct = new HashSet<ingridientsProduct>();
        }
    
        public string Name { get; set; }
        public double Count { get; set; }
        public double Price { get; set; }
        public int id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ingridientsProduct> ingridientsProduct { get; set; }
    }
}
